2d:
	mpicxx -g -Wall -o k_means_seg_serial k_means_seg_serial.cpp `pkg-config opencv --cflags opencv` `pkg-config --libs opencv` -lm -lopencv_highgui -lopencv_imgproc

bla:
	mpicxx -g -Wall -o test1 test1.cpp `pkg-config opencv --cflags opencv` `pkg-config --libs opencv` -lm -lopencv_highgui -lopencv_imgproc

3d:
	mpicxx -g -Wall -Og -o k_means_3D_seg_serial k_means_3D_seg_serial.cpp `pkg-config opencv --cflags opencv` `pkg-config --libs opencv` -lm -lopencv_highgui -lopencv_imgproc